apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-vault
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@retter.io
    privateKeySecretRef:
      name: letsencrypt-vault
    solvers:
      - http01:
          ingress:
            class: nginx