apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-resource
  namespace: default
  annotations:
    "helm.sh/resource-policy": delete
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-auth
    serviceAccount: vault-auth
