---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-auth
rules:
  - apiGroups: ['','auth/kubernetes/login']
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ['get', 'create', 'list', 'watch']
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs: ['create', 'get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-auth
subjects:
  - kind: ServiceAccount
    name: vault-auth # This should match the service account used by your Vault pods
    namespace: default # This should match the namespace where Vault is deployed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretproviderclasses-rolebinding-2
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default  # adjust if your namespace is different
roleRef:
  kind: ClusterRole
  name: secretproviderclasses-role
  apiGroup: rbac.authorization.k8s.io