apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "replicasets"]
    verbs: ["get", "list", "watch"]