
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: loki
    namespace: monitoring
    chart: ./loki

  - name: prometheus
    namespace: monitoring
    chart: ./prometheus

  - name: grafana
    namespace: monitoring
    chart: ./grafana

  - name: redis
    chart: ./redis

  - name: rabbitmq
    chart: ./rabbitmq

  - name: scheduler-redis
    chart: ./scheduler-redis

  - name: mongo
    chart: ./mongo

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx

  - name: minio-operator
    namespace: minio
    chart: ./minio-operator

  - name: minio-tenant
    namespace: minio
    chart: ./minio-tenant

  - name: external-secrets
    namespace: default
    chart: ./external-secrets

  - name: vault
    namespace: default
    chart: ./vault

  - name: jenkins
    namespace: default
    chart: ./jenkins

  - name: external-secrets
    namespace: default
    chart: ./external-secrets
