repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
#  - name: loki
#    namespace: monitoring
#    chart: ./loki
#    values:
#      -  ./loki/values.yaml
#      - ./storage-class-overrides.yaml
#
#  - name: prometheus
#    namespace: monitoring
#    chart: ./prometheus
#    values:
#      -  ./prometheus/values.yaml
#      - ./storage-class-overrides.yaml
#
#  - name: grafana
#    namespace: monitoring
#    chart: ./grafana
#    values:
#      -  ./grafana/values.yaml
#      - ./storage-class-overrides.yaml

  - name: redis
    chart: ./redis
    values:
      - ./redis/values.yaml
      - ./storage-class-overrides.yaml

  - name: rabbitmq
    chart: ./rabbitmq
    values:
      - ./rabbitmq/values.yaml
      - ./storage-class-overrides.yaml

  - name: scheduler-redis
    chart: ./scheduler-redis
    values:
      - ./scheduler-redis/values.yaml
      - ./storage-class-overrides.yaml

  - name: mongo
    chart: ./mongo
    values:
      - ./mongo/values.yaml
      - ./storage-class-overrides.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx

  - name: minio-operator
    namespace: minio
    chart: ./minio-operator

  - name: minio-tenant
    namespace: minio
    chart: ./minio-tenant
    values:
      - ./minio-tenant/values.yaml
      - ./storage-class-overrides.yaml

  - name: external-secrets
    namespace: default
    chart: ./external-secrets

  - name: vault
    namespace: default
    chart: ./vault
    values:
      - ./vault/values.yaml
      - ./storage-class-overrides.yaml

#  - name: jenkins
#    namespace: default
#    chart: ./jenkins

