projects:
  root:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    branch: main
    extraEnv:
      fromSecret:
        - redis-secrets
        - jenkins-secrets
        - minio-secrets
        - config-secret
        - config-storage
    jobs:
      init: root/init.Jenkinsfile
      rescue: root/rescue.Jenkinsfile
      build: user-code-template/build.Jenkinsfile
      deploy: user-code-template/deploy.Jenkinsfile
  vault-manager:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    branch: main
    jobs:
      deploy: vault-manager/deploy.Jenkinsfile
  console:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    branch: main
    jobs:
      build: console/build.Jenkinsfile
      deploy: console/deploy.Jenkinsfile
