jenkins:
    systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
    numExecutors: 5
    mode: NORMAL
    scmCheckoutRetryCount: 3
    labelString: "master-node"
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: "${JENKINS_REMOTE_USER}"
                  name: "${JENKINS_REMOTE_USER}"
                  password: "${JENKINS_REMOTE_TRIGGER_TOKEN}"
                  properties:
                      - mailer:
                            emailAddress: "jenkins@retter.io"
    authorizationStrategy:
        loggedInUsersCanDoAnything:
            allowAnonymousRead: false



jobs:
  - script: >
      pipelineJob('project-setup') {
        description('Pipeline job for project setup')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:rettersoft/rio-kubernetes-project-setup.git')
                }
                branches('*/main')
              }
            }
            scriptPath('setup.Jenkinsfile')
          }
        }
        authenticationToken('')          
      }

  - script: >
      pipelineJob('project-config') {
        description('Pipeline job for project setup')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:rettersoft/rio-kubernetes-project-setup.git')
                }
                branches('*/main')
              }
            }
            scriptPath('config.Jenkinsfile')
          }
        }
        authenticationToken('')          
      }

tool:
  nodejs:
    installations:
      - name: "node22.8.x"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "22.8.0"
                    npmPackages: pnpm ts-node@10.9.1 typescript@5.0.3


