jenkins:
  jenkinsUser: "admin"
  jenkinsPassword: "admin123"
  plugins:
    - workflow-aggregator
    - pipeline-stage-view
    - git
    - pipeline-github-lib
    - job-dsl
    - configuration-as-code
    - nodejs
    - docker-commons
    - docker-workflow
    - parameterized-trigger
    - http_request
    - kubernetes # TCP does not WORK choose websocket when configuring

  resources:
    limits:
      cpu: 2
      memory: "2096Mi"     # Maximum memory allowed (4 GB)

  persistence:
    enabled: true
    storageClass: "csi-disk"

  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 999
    # for docker :(


  extraVolumes:
    - name: ssh-key
      secret:
        secretName: jenkins-ssh-key
        defaultMode: 0600
    - name: ssh-key-renamed
      emptyDir: { }
    - name: jenkins-casc-config
      configMap:
        name: jenkins-casc-config
    - name: projects-config
      configMap:
        name: jenkins-projects-config
        ##newly added

  extraVolumeMounts:
#    - name: ssh-key-renamed
#      mountPath: /bitnami/jenkins/.ssh
    - name: jenkins-casc-config
      mountPath: /bitnami/jenkins/casc_configs
    - name: projects-config
      mountPath: /bitnami/jenkins/projects-config


  # for docker :(
  agent:
    enabled: true
    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 999
      privileged: true
    resources:
      limits:
        cpu: 2
        memory: "2096Mi"     # Maximum memory allowed (4 GB)


  # for docker :(
  rbac:
    create: true
  # for docker :(
  serviceAccount:
    create: true
    name: "jenkins"


  extraEnvVars:
#    - name: GIT_SSH_COMMAND
#      value: "ssh -i /bitnami/jenkins/.ssh/id_rsa -o StrictHostKeyChecking=no"
    - name: CASC_JENKINS_CONFIG
      value: /bitnami/jenkins/casc_configs/jenkins.yaml
    - name: JENKINS_REMOTE_TRIGGER_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: JENKINS_REMOTE_TRIGGER_TOKEN
    - name: JENKINS_REMOTE_USER
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: JENKINS_REMOTE_USER


#  initContainers:
#    - name: setup-ssh
#      image: bitnami/git:latest
#      securityContext:
#        runAsUser: 1001
#        runAsGroup: 1001
#      command:
#        - /bin/sh
#        - -c
#        - |
#          cp /tmp/ssh-key/ssh-privatekey /tmp/ssh-key-renamed/id_rsa
#          cp /tmp/ssh-key/ssh-publickey /tmp/ssh-key-renamed/id_rsa.pub
#          chmod 600 /tmp/ssh-key-renamed/id_rsa
#          chmod 644 /tmp/ssh-key-renamed/id_rsa.pub
#          ssh-keyscan github.com >> /tmp/ssh-key-renamed/known_hosts
#      volumeMounts:
#        - name: ssh-key
#          mountPath: /tmp/ssh-key
#        - name: ssh-key-renamed
#          mountPath: /tmp/ssh-key-renamed


  global:
    defaultStorageClass: csi-disk