{{- if .Values.enabled }}
{{- range $index, $className := .Values.global.classes }}
{{- $modifiedQueueName := regexReplaceAll "[^a-z0-9]+" "-"  (lower (substr 0 20 $className)) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
  labels:
    app: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
    {{- with .Values.global.podExtraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
  template:
    metadata:
      labels:
        app: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
       {{- with .Values.global.podExtraLabels }}
       {{ toYaml . | nindent 8 }}
       {{- end }}

    spec:
      dnsPolicy: ClusterFirst

      containers:
        - name: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if $.Values.command }}
          command: {{ $.Values.command | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: {{ include "rio-watcher-socket-io.fullname" $ }}-{{ $modifiedQueueName }}
            - name: RELEASE_NAME
              value: {{ $.Release.Name }}
            - name: CLASS_NAME
              value: {{ $className }}
            {{- range $key, $value := $.Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $.Values.global.envFrom }}
            {{- toYaml $.Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
            - containerPort: {{ $.Values.service.debugPort }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys

{{- end -}}
{{- end }}