{{/*{{- define "my-stream-watcher.chunked-deployments" -}}*/}}
{{/*{{- $chunkSize := .Values.chunkSize | int -}}*/}}
{{/*{{- $collections := .Values.collections -}}*/}}
{{/*{{- $total := len $collections -}}*/}}

{{/*{{- /* If there are no collections, render nothing. */ -}}*/}}
{{/*{{- if eq $total 0 -}}*/}}
{{/*  # No collections to watch*/}}
{{/*{{- else -}}*/}}
{{/*  */}}
{{/*      # Calculate how many chunks we need.*/}}
{{/*      # Example: if total=12 and chunkSize=5,*/}}
{{/*      # numChunks = ceil(12/5) = 3*/}}
{{/*      # We'll do that using integer math trick:*/}}
{{/*      # numChunks = (total + chunkSize -1) / chunkSize*/}}
{{/*    */}}
{{/*  {{- $numChunks := div (add $total (sub $chunkSize 1)) $chunkSize -}}*/}}

{{/*  {{- /* Now we iterate over the chunk indexes from 0..(numChunks-1). */ -}}*/}}
{{/*  {{- range $chunkIndex := until $numChunks }}*/}}
{{/*---*/}}
{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: watch-stream-{{ $chunkIndex }}*/}}
{{/*  labels:*/}}
{{/*    app: watch-stream*/}}
{{/*    chunk: "{{ $chunkIndex }}"*/}}
{{/*spec:*/}}
{{/*  replicas: 1*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: watch-stream*/}}
{{/*      chunk: "{{ $chunkIndex }}"*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: watch-stream*/}}
{{/*        chunk: "{{ $chunkIndex }}"*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - name: watch-stream*/}}
{{/*          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"*/}}
{{/*          imagePullPolicy: "{{ .Values.image.pullPolicy }}"*/}}
{{/*          env:*/}}
{{/*            - name: MONGO_COLLECTIONS*/}}
{{/*              # Slice the array from start to end for this chunk*/}}
{{/*              value: "{{ */}}
{{/*                join "," (slice */}}
{{/*                            $collections */}}
{{/*                            (mul $chunkIndex $chunkSize) */}}
{{/*                            (min (mul (add $chunkIndex 1) $chunkSize) $total)) */}}
{{/*              }}"*/}}
{{/*            - name: MONGO_URI*/}}
{{/*              value: "{{ .Values.env.MONGO_URI }}"*/}}
{{/*  {{- end -}}*/}}
{{/*{{- end -}}*/}}
{{/*{{- end -}}*/}}
