apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.name" . }}
  labels:
    app: {{ include "mongo.name" . }}
spec:
  serviceName: "mongo"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources: {{ toYaml .Values.resources | indent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations: {{ toYaml .Values.tolerations | indent 8 }}
      affinity: {{ toYaml .Values.affinity | indent 8 }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}