apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-secret-external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: config-secret
    creationPolicy: Owner
  dataFrom:
      - extract:
          key: "{{ .Values.vault.kvPath }}/data/config"
          property: custom