apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-external-secret
spec:
  refreshInterval: "1h"  # Adjust as needed  
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: config
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/config"
        property: storage