apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      auth:
        serviceAccount:
          name: vault-auth
          namespace: default
      server:
        apiServerURL: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-public
          key: ca.crt