apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend
spec:
  provider:
    kubernetes:
      auth:
        # Use the operator's service account for authentication
        serviceAccount:
          name: external-secrets-operator
      remoteNamespace: default