apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: object-storage-external-secret
  namespace: "default"
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: object-storage-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ .Values.vault.kvPath }}/data/OBJECT_STORAGE"
