apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-helm
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - pods/exec
      - pods/log
      - services
      - services/status
      - configmaps
      - secrets
      - endpoints
      - persistentvolumeclaims
      - events
      - replicationcontrollers
      - replicationcontrollers/scale
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources:
      - deployments
      - deployments/scale
      - daemonsets
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - ingresses/status
      - networkpolicies
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [ "external-secrets.io" ]
    resources:
      - externalsecrets
      - secretstores
      - clustersecretstores
    verbs: [ "create", "get", "list", "watch", "update", "patch", "delete" ]

