{{- $secretName := printf "%s-secrets" .Release.Name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  JENKINS_REMOTE_USER:  {{ "api-user" | b64enc | quote }}
  JENKINS_REMOTE_TRIGGER_TOKEN: {{ randAlphaNum 20 | b64enc }}
  JENKINS_HOST: {{ "http://jenkins.default.svc.cluster.local" | b64enc | quote }}