replicaCount: 1

# for x86 use this
image:
  repository: mongo
  tag: 7
  pullPolicy: IfNotPresent

# for arm64 use this instead
#image:
#  repository: arm64v8/mongo
#  tag: 7.0
#  pullPolicy: IfNotPresent
#
service:
  type: ClusterIP
  port: 27017

mongodb:
  username: admin
  password: password
  database: mydatabase

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  storageClassName: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
