jenkins:
    systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
    numExecutors: 5
    mode: NORMAL
    scmCheckoutRetryCount: 3
    labelString: "master-node"
    nodes:
        - permanent:
              name: "agent1"
              numExecutors: 5
              remoteFS: "/home/jenkins/agent"
              launcher:
                jnlp:
                  workDirSettings:
                    disabled: false
                    internalDir: "remoting"
                    failIfWorkDirIsMissing: false
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: "${JENKINS_REMOTE_USER}"
                  name: "${JENKINS_REMOTE_USER}"
                  password: "${JENKINS_REMOTE_TRIGGER_TOKEN}"
                  properties:
                      - mailer:
                            emailAddress: "jenkins@retter.io"
    authorizationStrategy:
        loggedInUsersCanDoAnything:
            allowAnonymousRead: false
    globalNodeProperties:
      - envVars:
          env:
            - key: CLOUD_PROVIDER
              value: "${CLOUD_PROVIDER}"
            - key: CLUSTER_NAME
              value: "${CLUSTER_NAME}"
            - key: CLUSTER_PROJECT
              value: "${CLUSTER_PROJECT}"
            - key: CLUSTER_REGION_OR_ZONE
              value: "${CLUSTER_REGION_OR_ZONE}"

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ssh-key"
              description: "SSH key for Git access"
              username: "msacar"
              passphrase: ""
              privateKeySource:
                directEntry:
                  privateKey: "patates"
          - file:
              id: "kube-config"
              scope: GLOBAL
              description: "kube config"
              fileName: "config"
              secretBytes: "{+Eb1J5s+OmcHcFwh01//EN8KgWdttODlJs3lBG+QtK8=}"
          - string:
              scope: GLOBAL
              id: "docker-credentials"
              description: "docker credentials"
              secret: "{AQAAABAAAAAQlxnkJNIgAmTWPSqQGTXkjtAKzZDGDZ+6iBb9SZ1kuqk=}"



jobs:
  - script: >
      pipelineJob('project-config') {
        description('Build the dynamic project-config.yaml from MongoDB')
        definition {
          cps {
            script("""
              @Library('retter@main') _
              generateProjectConfig()
            """.stripIndent())
          }
        }
        authenticationToken('')          
      }

  - script: >
      pipelineJob('project-setup') {
        description('Seed all per-project folders & pipelineJobs via Job-DSL')
        definition {
          cps {
            script("""
              @Library('retter@main') _
              seedProjects()
            """.stripIndent())
              }
            }
      }


unclassified:
  globalLibraries:
    libraries:
      - name: "retter"
        defaultVersion: "main"
        allowVersionOverride: true
        implicit: false
        includeInChangesets: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "git@github.com:rettersoft/rio-kubernetes-jenkins-global-pipeline.git"
                credentialsId: "ssh-key"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false