fullnameOverride: rio-api
nameOverride: rio-api
replicaCount: 1
projectId: projectid3

image:
  repository: 130575395405.dkr.ecr.eu-west-2.amazonaws.com/retter-poc-rio-api
  tag: 13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  debugPort: 9229

imagePullSecrets:
  enabled: true
  secrets: 
    - name: ecr-secret

ingress:
  enabled: true
  path: /

initContainers:
  enabled: false

env:
  SERVICE_NAME: rio-api
  PROJECT_ID: projectid3
  REDIS_CONFIG: '{"host":"redis-master.default.svc.cluster.local","port":6379}'

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

command:
  - node
  - /opt/core-extension/dist/src/bin/api.js

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60