{{/*{{ range $index := until (int .Values.proxyGroup) }}*/}}
{{- range $queueName, $queueConfig := .Values.global.queues }}
{{- $modifiedQueueName := regexReplaceAll "[^a-z0-9]+" "-" (lower (substr 0 20 $queueName)) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-consumer.fullname" $ }}-class-{{ $modifiedQueueName }}
  labels:
    app: {{ include "proxy-consumer.fullname" $ }}-class-{{ $modifiedQueueName }}
    {{- with $.Values.global.podExtraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "proxy-consumer.fullname" $ }}-class-{{ $modifiedQueueName }}
  template:
    metadata:
      labels:
        app: {{ include "proxy-consumer.fullname" $ }}-class-{{ $modifiedQueueName }}
        {{- with $.Values.global.podExtraLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations: {{- toYaml $.Values.global.podAnnotations | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirst
      {{- if $.Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.global.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: queue-init
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          command: ["node", "/opt/core-extension/dist/src/init/init-fifo.js"]
          env:
{{/*            - name: PROXY_QUEUE_INDEX*/}}
{{/*              value: {{ $index | quote }}*/}}
{{/*            - name: PROXY_QUEUE_GROUP_SIZE*/}}
{{/*              value: {{  $.Values.proxyGroupSize | quote }}*/}}
            - name: RIO_CLASS_QUEUE_NAME
              value: {{ $queueName }}
            - name: RIO_QUEUE_PARTITIONS
              value: {{ $queueConfig.partitions | quote }}
            {{- range $key, $value := $.Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $.Values.global.envFrom }}
            {{- toYaml $.Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
      containers:
        - name: {{ include "proxy-consumer.fullname" $ }}-{{ $modifiedQueueName }}
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          {{- if $.Values.class.command }}
          command: {{ $.Values.class.command | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: {{ include "proxy-consumer.name" $ }}
            - name: RELEASE_NAME
              value: {{ $.Release.Name }}
            - name: REDIS_CONFIG
              value: '{"host":"redis-master.default.svc.cluster.local","port":6379}'
{{/*            - name: PROXY_QUEUE_INDEX*/}}
{{/*              value: {{ $index | quote }}*/}}
{{/*            - name: PROXY_QUEUE_GROUP_SIZE*/}}
{{/*              value: {{  $.Values.proxyGroupSize | quote }}*/}}
            - name: RIO_CLASS_QUEUE_NAME
              value: {{ $queueName }}
            - name: RIO_QUEUE_PARTITIONS
              value: {{ $queueConfig.partitions | quote }}
            {{- range $key, $value := $.Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $.Values.global.envFrom }}
            {{- toYaml $.Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
{{/*            - configMapRef:*/}}
{{/*                name: proxy-queues-config-map*/}}
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
            - containerPort: {{ $.Values.service.debugPort }}
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml $.Values.tolerations | nindent 8 }}
      affinity: {{ toYaml $.Values.affinity | nindent 8 }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
{{- end }}
