{{- $proxyGroup := int .Values.global.proxyGroup -}}
{{- range $index := until $proxyGroup }}

  # If you were to use .Values within a range loop, it might cause unintended behavior
# because .Values would be scoped to the loop's current item if not override,
# which might not have the .Values fields:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-consumer.fullname" $ }}-{{ $index }}
  labels:
    app: {{ include "proxy-consumer.fullname" $ }}-{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "proxy-consumer.fullname" $ }}-{{ $index }}
  template:
    metadata:
      labels:
        app: {{ include "proxy-consumer.fullname" $ }}-{{ $index }}
      annotations: {{- toYaml $.Values.global.podAnnotations | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirst
      {{- if $.Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.global.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: queue-init
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          command: ["node", "/opt/core-extension/dist/src/init/init-fifo-chunk.js"]
          env:
            - name: PROXY_QUEUE_INDEX
              value: {{ $index }}
            - name: PROXY_QUEUE_GROUP_SIZE
              value: {{  .Values.global.proxyGroup }}
            {{- range $key, $value := $.Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $.Values.global.envFrom }}
            {{- toYaml $.Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
            - configMapRef:
                name: proxy-queues-config-map
      containers:
        - name: {{ include "proxy-consumer.fullname" $ }}-{{ $index }}
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}"
          {{- if $.Values.command }}
          command: {{ $.Values.command | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: {{ include "proxy-consumer.name" $ }}
            - name: RELEASE_NAME
              value: {{ $.Release.Name }}
            - name: REDIS_CONFIG
              value: '{"host":"redis-master.default.svc.cluster.local","port":6379}'
            - name: PROXY_QUEUE_INDEX
              value: {{ $index }}
            - name: PROXY_QUEUE_GROUP_SIZE
              value: {{  .Values.global.proxyGroup }}
            {{- range $key, $value := $.Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $.Values.global.envFrom }}
            {{- toYaml $.Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if $.Values.envFrom }}
            {{- toYaml $.Values.envFrom | nindent 12 }}
            {{- end }}
            - configMapRef:
                name: proxy-queues-config-map
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
            - containerPort: {{ $.Values.service.debugPort }}
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml $.Values.tolerations | nindent 8 }}
      affinity: {{ toYaml $.Values.affinity | nindent 8 }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
{{- end }}