{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rio-watcher-client-server-socket-io.fullname" . }}
  labels:
    app: {{ include "rio-watcher-client-server-socket-io.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "rio-watcher-client-server-socket-io.fullname" . }}
{{- end }}
