global:
  scrape_interval: 10s
  scrape_timeout: 10s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
  evaluation_interval: 10s
prometheus:
  prometheusSpec:
    scrapeInterval: 10s      # Set Prometheus scrape interval to 10 seconds
    scrapeTimeout: 10s
    evaluationInterval: 10s  # Match evaluation interval
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true
  server:
    enabled: true
    persistentVolume:
      enabled: true
      size: 8Gi
    scrape:
      enabled: true
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
  global:
    scrape_interval: 10s
    scrape_timeout: 10s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText0.0.4
    evaluation_interval: 10s
  extraScrapeConfigs: |
    - job_name: 'kubelet'
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc.cluster.local:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}:10250/proxy/metrics/cadvisor



