global:
  env:
    PROJECT_ID: console
  certificate:
    # -- What type of TLS certificate should be used?
    #    Available options:
    #    1) custom: A user-provided certificate.
    #       - You must create your own secret, for example:
    #         kubectl create secret tls my-cert-tls \
    #           --cert /path/to/tls.crt \
    #           --key /path/to/tls.key
    #       - Reference that secret in your Helm chart as needed.
    #    2) letsencrypt: Automatically request a certificate from Let's Encrypt.
    #
    #    Default is "custom".
    type: custom

replicaCount: 1
image:
  repository: console
  tag: 11
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  debugPort: 9229

ingress:
  host: console.localhost
  certificateSecret: my-cert-tls
  enabled: true
  path: /


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60