{{- if eq .Values.global.certificate.type "letsencrypt" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-registry
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@retter.io
    privateKeySecretRef:
      name: letsencrypt-registry
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
