apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-secret-access
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
    ## newly added
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
  # Permissions for ExternalSecret CRD management
  - apiGroups: [ "external-secrets.io" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

  # Permissions to create and update events (for logging and debugging)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # Permissions to list/watch namespaces if the operator handles multiple namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  # (Optional) If the operator needs to inspect serviceaccounts, for example, if it uses them dynamically
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "list", "watch" ]
