apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-secret-external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: config-secret-root-api-key
    creationPolicy: Owner
  data:
    - secretKey: ROOT_PROJECT_API_KEY
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/config"
        property: secret.ROOT_PROJECT_API_KEY
