apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-external-secret
  namespace: {{ .Values.global.env.PROJECT_ID}}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_HOST
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/RABBITMQ"
        property: RABBITMQ_HOST
    - secretKey: RABBITMQ_PORT
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/RABBITMQ"
        property: RABBITMQ_PORT
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/RABBITMQ"
        property: RABBITMQ_USERNAME
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/RABBITMQ"
        property: RABBITMQ_PASSWORD
    - secretKey: RABBITMQ_CONNECTION_STRING
      remoteRef:
        key: "{{ .Values.vault.kvPath }}/data/RABBITMQ"
        property: RABBITMQ_CONNECTION_STRING