replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  debugPort: 9229

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

command:
  - node
  - /opt/core-extension/dist/src/bin/fifo-proxy.js
