projects:
  root:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    branch: main
    gitCredentials: ssh-key
    extraEnv:
      fromSecret:
        - redis-secrets
        - jenkins-secrets
        - object-storage-secrets
        - config-secret-root-api-key
        - config-storage
        - mongo-secrets
        - rabbitmq-secrets
    jobs:
      init: root/init.Jenkinsfile
      rescue: root/rescue.Jenkinsfile
      build: user-code-template/build.Jenkinsfile
      deploy: user-code-template/deploy.Jenkinsfile
  vault-manager:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    gitCredentials: ssh-key
    branch: main
    jobs:
      deploy: vault-manager/deploy.Jenkinsfile
  console:
    gitUrl: git@github.com:rettersoft/rio-kubernetes-jenkinsfiles.git
    gitCredentials: ssh-key
    branch: main
    jobs:
      build: console/build.Jenkinsfile
      deploy: console/deploy.Jenkinsfile
