apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" . }}
    spec:
      dnsPolicy: ClusterFirst
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets.secrets | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
        - name: {{ .Values.initContainers.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.initContainers.command }}
          command: {{ .Values.initContainers.command | toYaml | nindent 12 }}
          {{- end }}
          env:
          {{- range .Values.initContainers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ include "common.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.command }}
          command: {{ .Values.command | toYaml | nindent 12 }}
          {{- end }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
            {{- if .Values.service.debugPort }}
            - name: debug
              containerPort: {{ .Values.service.debugPort }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
