
loki:
  monitoring:
    selfMonitoring:
      enabled: false
  test:
    enabled: false
  loki:
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
    pattern_ingester:
      enabled: true

  deploymentMode: SimpleScalable

  backend:
#    affinity: {}
    replicas: 1
  read:
#    affinity: {}
    replicas: 1
  write:
#    affinity: {}
    replicas: 1 # To ensure data durability with replication
#
#  gateway:
#    service:
#      type: LoadBalancer