apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rio-api.fullname" . }}
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - localhost.com
      secretName: my-cert-tls
  ingressClassName: nginx
  rules:
    - host: localhost.com
      http:
        paths:
          - pathType: Prefix
            path: /{{ .Values.global.env.PROJECT_ID }}
            backend:
              service:
                name: {{ include "rio-api.fullname" . }}
                port:
                  number: 80
