apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rio-api.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  #TODO host should be dynamic
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: letsencrypt-prod
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /{{ .Values.global.env.PROJECT_ID }}
            backend:
              service:
                name: {{ include "rio-api.fullname" . }}
                port:
                  number: 80
