apiVersion: v2
name: redis
description: A Helm chart for managing redis
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: redis
    version: 19.3.2
    repository: "https://charts.bitnami.com/bitnami"
