redis:
  architecture: standalone
  auth:
    enabled: true
    password: password
  master:
    persistence:
      size: 4Gi
  replica:
    enabled: false
    replicaCount: 0
    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "512Mi"
  global:
    #storageClass: "hi-iops-ssd"