global:
  queues:
    - name: MainTests
      class: MainTests
      partitions: 1
      consumers:
        - 0-1
    - name: FifoTests
      class: FifoTests
      partitions: 1
      consumers:
        - 0-1
  env:
    PROJECT_ID: projectid3
    MINIO_SECRET_KEY: 'XEZrQDtB6NfYuaEamniUj8aOhT25C6nGWNCqBB6q'
    USER_CODE_URL: 'http://projectid3-user-code.default.svc.cluster.local'
    SCHEDULER_API_URL: 'http://projectid3-rio-scheduler-api.default.svc.cluster.local'
    RDK_URL: 'http://projectid3-rio-rdk.default.svc.cluster.local'
  envFrom:
    - secretRef:
        name: rabbitmq-secrets
    - secretRef:
        name: mongo-secrets
    - secretRef:
        name: minio-secrets
    - secretRef:
        name: redis-secrets
    - secretRef:
        name: scheduler-redis-secrets
  podAnnotations: { }
  image:
    repository: projectid3
    tag: 116
    pullPolicy: IfNotPresent