global:
  queues:
    - name: MainTests
      class: MainTests
      partitions: 1
      consumers:
        - 0-1
    - name: FifoTests
      class: FifoTests
      partitions: 1
      consumers:
        - 0-1
  destinations:
    - name: state_stream_firestore
      class: state_stream_firestore
      partitions: 1
      consumers:
        - 0-1
  env:
    PROJECT_ID: ${PROJECT_ID}
    MINIO_SECRET_KEY: 'XEZrQDtB6NfYuaEamniUj8aOhT25C6nGWNCqBB6q'
    USER_CODE_URL: 'http://${PROJECT_ID}-user-code.default.svc.cluster.local'
    SCHEDULER_API_URL: 'http://${PROJECT_ID}-rio-scheduler-api.default.svc.cluster.local'
    RDK_URL: 'http://${PROJECT_ID}-rio-rdk.default.svc.cluster.local'
  envFrom:
    - secretRef:
        name: rabbitmq-secrets
    - secretRef:
        name: mongo-secrets
    - secretRef:
        name: object-storage-secrets
    - secretRef:
        name: redis-secrets
    - secretRef:
        name: scheduler-redis-secrets
    - secretRef:
        name: config-storage
  podAnnotations: { }
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent

proxy-consumer:
  proxyGroup: 2
  proxyGroupSize: 2

destination-consumer:
  command:
    - node
    - /opt/core-extension/dist/src/bin/fifo-destination-consumer.js