apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "console.fullname" . }}
spec:
  # TODO should be dynamic
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.certificateSecret }}
  ingressClassName: nginx
  rules:
    - host: console.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "console.fullname" . }}
                port:
                  number: 80
