apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "console.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: console.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "console.fullname" . }}
                port:
                  number: 80
