replicaCount: 1


command:
  - node
  - /opt/core-extension/dist/src/bin/user-code.js

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  debugPort: 9229

resources:
  limits:
    cpu: 500m
    memory: 528Mi
  requests:
    cpu: 500m
    memory: 228Mi

nodeSelector: {}

tolerations: []

affinity: {}
global:
  podAnnotations:
  env:
    TEST_OTP: "123456"
    PROJECT_ID: ${PROJECT_ID}
    USER_CODE_URL: 'http://${PROJECT_ID}-user-code.default.svc.cluster.local'
    SCHEDULER_API_URL: 'http://${PROJECT_ID}-rio-scheduler-api.default.svc.cluster.local'
    RDK_URL: 'http://${PROJECT_ID}-rio-rdk.default.svc.cluster.local'
  envFrom:
    - secretRef:
       name: rabbitmq-secrets
    - secretRef:
        name: mongo-secrets
    - secretRef:
        name: minio-secrets
    - secretRef:
        name: redis-secrets
    - secretRef:
        name: scheduler-redis-secrets
  secret:
    MINIO_USERNAME: "minio"
    MINIO_PASSWORD: "minio123"
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent


rio-api:
  ingress:
    enabled: true
    canary: false
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
  resources:
    limits:
      cpu: 100m
      memory: 228Mi
    requests:
      cpu: 100m
      memory: 228Mi
  command:
    - node
    - /opt/core-extension/dist/src/bin/api.js

rio-scheduler-task-consumer:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-task-consumer.js

rio-scheduler-async-consumer:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-async-consumer.js

rio-scheduler-cron-consumer:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-cron-consumer.js

rio-scheduler-api:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-api.js

rio-scheduler-dashboard:
  image:
    repository: mstkk/bulldashboard
    tag: latest
    pullPolicy: Always
  queues:
    - ${PROJECT_ID}_async
    - ${PROJECT_ID}_task
    - ${PROJECT_ID}_cron

rio-rdk:
  resources:
    limits:
      cpu: 100m
      memory: 228Mi
    requests:
      cpu: 100m
      memory: 228Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/rdk.js
