replicaCount: 1

image:
  repository: ${REPOSITORY}
  tag: ${IMAGE_TAG}
  pullPolicy: IfNotPresent
command:
  - node
  - /opt/core-extension/dist/src/bin/user-code.js

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  debugPort: 9229

resources:
  limits:
    cpu: 500m
    memory: 528Mi
  requests:
    cpu: 500m
    memory: 228Mi

nodeSelector: {}

tolerations: []

affinity: {}
global:
  podAnnotations:
  env:
    PROJECT_ID: projectid3
    USER_CODE_URL: 'http://projectid3-user-code.default.svc.cluster.local'
    SCHEDULER_API_URL: 'http://projectid3-rio-scheduler-api.default.svc.cluster.local'
    RDK_URL: 'http://projectid3-rio-rdk.default.svc.cluster.local'
  envFrom:
    - secretRef:
       name: rabbitmq-secrets
    - secretRef:
        name: mongo-secrets
    - secretRef:
        name: minio-secrets
    - secretRef:
        name: redis-secrets
    - secretRef:
        name: scheduler-redis-secrets

  secret:
    MINIO_USERNAME: "minio"
    MINIO_PASSWORD: "minio123"


rio-api:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    path: /projectid3
    canary: false
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
  resources:
    limits:
      cpu: 100m
      memory: 228Mi
    requests:
      cpu: 100m
      memory: 228Mi
  command:
    - node
    - /opt/core-extension/dist/src/bin/api.js

rio-scheduler-task-consumer:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-task-consumer.js

rio-scheduler-async-consumer:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-async-consumer.js

rio-scheduler-cron-consumer:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-cron-consumer.js

rio-scheduler-api:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/scheduler-api.js

rio-scheduler-dashboard:
  image:
    repository: mstkk/bulldashboard
    tag: latest
    pullPolicy: Always
  queues:
    - projectid3_async
    - projectid3_task
    - projectid3_cron

rio-rdk:
  image:
    repository: ${REPOSITORY}
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 228Mi
    requests:
      cpu: 100m
      memory: 228Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  command:
    - node
    - /opt/core-extension/dist/src/bin/rdk.js
