harbor:
  logLevel: debug
  # values.yaml
  externalURL: "https://registry.localhost"             # Replace with your hostname or IP
  harborAdminPassword: "123123"                         # Default admin password
  persistence:
    enabled: true
    resourcePolicy: "delete"
    persistentVolumeClaim:
      registry:
        storageClass: ""                      # Or your storage class
        size: 5Gi
      jobservice:
        storageClass: "local-path"
        size: 1Gi
  service:
    type: ClusterIP                                     # Use NodePort for direct port access
    port: 80
  expose:
    type: ingress                   # ingress, clusterIP, nodePort, or loadBalancer
    tls:
      enabled: true                 # enable or disable TLS
      certSource: secret              # auto‑generate certs (auto, secret, or none)
      secret:
        secretName: "my-cert-tls"
    ingress:
      hosts:
        core: registry.localhost    # must match externalURL domain
      controller: default           # ingress controller type (default, gce, ncp, etc.)
      className: "nginx"                 # optionally set IngressClass for K8s ≥1.18
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"

