apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.global.env.PROJECT_ID }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@retter.io
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.global.env.PROJECT_ID }}
    solvers:
      - http01:
          ingress:
            class: nginx