apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rio-scheduler-async-consumer.fullname" . }}
  labels:
    app: {{ include "rio-scheduler-async-consumer.fullname" . }}
    {{- with .Values.global.podExtraLabels }}
    {{ toYaml . | nindent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rio-scheduler-async-consumer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "rio-scheduler-async-consumer.fullname" . }}
        {{- with .Values.global.podExtraLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations: {{- toYaml .Values.global.podAnnotations | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirst
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ include "rio-scheduler-async-consumer.fullname" . }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          {{- if .Values.command }}
          command: {{ .Values.command | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: {{ include "rio-scheduler-async-consumer.name" . }}
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: REDIS_CONFIG
              value: '{"host":"redis-master.default.svc.cluster.local","port":6379}'
            {{- range $key, $value := .Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if .Values.global.envFrom }}
            {{- toYaml .Values.global.envFrom | nindent 12 }}
            {{- end }}
            {{- if .Values.envFrom }}
            {{- toYaml .Values.envFrom | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
            - containerPort: {{ .Values.service.debugPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
