
vault:
  role: "vault-auth"
  kvPath: "secret"
  address: "http://vault:8200"
  secretVersion: "1"

  initialSecrets:
    - path: "RABBITMQ"
      data:
        RABBITMQ_HOST: 'rabbitmq.default.svc.cluster.local'
        RABBITMQ_PORT: "5672"
        RABBITMQ_USERNAME: 'new-user'
        RABBITMQ_PASSWORD: 'new-password'
        RABBITMQ_CONNECTION_STRING: 'amqp://new-user:new-password@rabbitmq.default.svc.cluster.local'
    - path: "REDIS"
      data:
        REDIS_MODE: 'standalone'
        REDIS_HOST: 'redis-master.default.svc.cluster.local'
        REDIS_PORT: 6379
        REDIS_PASSWORD: 'password'
    - path: "SCHEDULER_REDIS"
      data:
        SCHEDULER_REDIS_MODE: 'standalone'
        SCHEDULER_REDIS_HOST: 'redis-master.default.svc.cluster.local'
        SCHEDULER_REDIS_PORT: 6379
        SCHEDULER_REDIS_PASSWORD: 'password'
    - path: "MONGO"
      data:
        MONGO_CONNECTION_STRING: 'mongodb://admin:password@mongo.default.svc.cluster.local:27017'
    - path: "OBJECT_STORAGE"
      data:
        OBJECT_STORAGE_TYPE: 'minio'
        OBJECT_STORAGE_HOST: 'minio.minio.svc.cluster.local'
        OBJECT_STORAGE_PORT: 443
        OBJECT_STORAGE_ACCESS_KEY: 'admin'
        OBJECT_STORAGE_SECRET_KEY: 'XEZrQDtB6NfYuaEamniUj8aOhT25C6nGWNCqBB6q'
    - path: "JENKINS"
      data:
        JENKINS_HOST: 'http://jenkins.default.svc.cluster.local:8080'
        JENKINS_REMOTE_TRIGGER_TOKEN: 'api-user'
        JENKINS_REMOTE_USER: 'api-user'
