rabbitmq:
  auth:
    username: new-user
    password: new-password
  extraPlugins: "rabbitmq_consistent_hash_exchange rabbitmq_delayed_message_exchange"
  clustering:
    enabled: false
  global:
    storageClass: "cbs"
  persistence:
    size: 4Gi