{{- range $index, $queue := .Values.global.queues }}
{{- range $consumerIndex, $consumer := $queue.consumers }}
{{- $modifiedQueueName := regexReplaceAll "[^a-z0-9]+" "-" (lower (substr 0 20 $queue.name)) }}

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "main-consumer.fullname" $ }}-{{ $modifiedQueueName }}-{{ $consumerIndex }}
  labels:
    app: {{ include "main-consumer.fullname" $ }}-{{ $modifiedQueueName }}-{{ $consumerIndex }}
spec:
  scaleTargetRef:
    name: {{ include "main-consumer.fullname" $ }}-{{ $modifiedQueueName }}-{{ $consumerIndex }}
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 7
  triggers:
    - type: rabbitmq
      metadata:
        queueName: {{ printf "%s_%s_0" $.Values.global.env.PROJECT_ID $queue.name | quote }}
        queueLength: "1"
        protocol: amqp
      authenticationRef:
        name: rio-fifo-keda-auth
{{- end }}
{{- end }}
