apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rio-fifo-keda-auth
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secrets
      key: RABBITMQ_CONNECTION_STRING
