apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.global.env.PROJECT_ID}}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: letsencrypt-prod
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: letsencrypt-prod