{{- range $index, $secretName := .Values.extraEnvFromSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Values.global.env.PROJECT_ID }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
    - remoteRef:
        key: {{ $secretName }}
---
{{- end }}