apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-cert-tls
  namespace: {{ .Values.global.env.PROJECT_ID}}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jenkins-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ .Values.vault.kvPath }}/data/JENKINS"


