apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: {{ .Values.global.env.PROJECT_ID}}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ .Values.vault.kvPath }}/data/MINIO"
