apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-tls-secret
  namespace: {{ .Values.global.env.PROJECT_ID}}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: my-tls-secret
    creationPolicy: Owner
    type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: my-tls-secret
