apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-cert-tls
  namespace: {{ .Values.global.env.PROJECT_ID}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: my-cert-tls
    creationPolicy: Owner
    type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: my-cert-tls
