apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-upgrade-install-{{ now | date "20060102150405" }}"
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      containers:
        - name: "{{ .Release.Name }}-post-upgrade-install"
          image: "{{ .Values.global.userImage.repository }}:{{ .Values.global.userImage.tag }}"
          imagePullPolicy: Always
          command:
            - node
            - /opt/core-extension/dist/src/hooks/post-hook.js
          env:
            - name: PROJECT_ID
              value: {{ .Values.global.env.PROJECT_ID }}
          envFrom:
            - secretRef:
                name: redis-secrets
      restartPolicy: Never
  backoffLimit: 2

