apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    version: 0.1

    log:
      level: debug

    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      cache:
        blobdescriptor: inmemory
    delete:
      enabled: true

    http:
      max_blob_chunk_size: 16777216
      disable:
        redirect: true
      debug:
        addr: :5001
      addr: :5000
      net: tcp
      headers:
        X-Content-Type-Options:
          - nosniff

    validation:
      disabled: true

    compatibility:
      schema1:
        enabled: false
