apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:3
          ports:
            - containerPort: 5000
            - containerPort: 5001
          volumeMounts:
            - name: image-storage
              mountPath: /var/lib/registry
            - name: registry-config
              mountPath: /etc/docker/registry/config.yml
              subPath: config.yml
      volumes:
        - name: registry-config
          configMap:
            name: registry-config
        - name: image-storage
          persistentVolumeClaim:
            claimName: registry-pvc