{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: docker-registry*/}}
{{/*spec:*/}}
{{/*  type: ClusterIP  # Changed from NodePort to ClusterIP*/}}
{{/*  selector:*/}}
{{/*    app: docker-registry*/}}
{{/*  ports:*/}}
{{/*    - port: 5000  # Changed to match the targetPort*/}}
{{/*      targetPort: 5000*/}}

apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: docker-registry