# .github/workflows/helm-push-local.yml
name: Publish rio-local Helm Charts

on:
  push:
    branches: [ ready-for-dev ]

permissions:
  contents: read

jobs:
  detect-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.find-charts.outputs.charts }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: find-charts
        name: Detect rio-local charts
        run: |
          CHARTS=$(find charts/rio-local -type f -name Chart.yaml \
            -exec dirname {} \; \
            | sed 's|charts/rio-local/||' \
            | jq -R -s -c 'split("\n")[:-1]')
          # Default to empty array if none found
          echo "charts=${CHARTS:-[]}" >> $GITHUB_OUTPUT

  publish:
    needs: detect-charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJson(needs.detect-charts.outputs.charts) }}
      fail-fast: false
      max-parallel: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" \
            | helm registry login k8-harbor.retter.io \
              --username "${{ secrets.HARBOR_USERNAME }}" \
              --password-stdin

      - name: Package & Push chart ${{ matrix.chart }}
        working-directory: charts/rio-local/${{ matrix.chart }}
        run: |
          helm dependency update . || true
          helm package .
          helm push *.tgz oci://k8-harbor.retter.io/rio-kubernetes-charts
