name: Release Helm Charts
on:
  push:
    branches: [ ready-for-dev ]
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read version file
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: azure/setup-helm@v4.3.0
        id: install

      - name: Bump all chart versions
        run: |
          export NEW_VERSION="${{ steps.read_version.outputs.VERSION }}"
          for chart in rio-project console vault-manager; do
            yq eval -i '
              .version = strenv(NEW_VERSION) |
              .appVersion = strenv(NEW_VERSION)
            ' charts/rio-projects/$chart/Chart.yaml
          done

      - name: Commit version bump
        uses: EndBug/add-and-commit@v9
        with:
          add: 'charts/rio-projects/*/Chart.yaml'
          message: "chore: bump all charts to ${{ steps.read_version.outputs.VERSION }}"
          fetch: '--tags --force'

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" \
            | helm registry login k8-harbor.retter.io \
              --username "${{ secrets.HARBOR_USERNAME }}" \
              --password-stdin

      - name: Package & push all charts
        run: |
          export NEW_VERSION="${{ steps.read_version.outputs.VERSION }}"
          for chart in rio-project console vault-manager; do
            helm dependency update charts/rio-projects/$chart
            helm package charts/rio-projects/$chart \
              --version "$NEW_VERSION" --app-version "$NEW_VERSION"
            helm push "${chart}-${NEW_VERSION}.tgz" \
              oci://k8-harbor.retter.io/rio-project-charts
          done
