name: Update VERSION File

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version"
        required: true
        type: string

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Overwrite VERSION
        run: |
          echo "${{ github.event.inputs.version }}" > VERSION

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git diff --quiet --exit-code || (
            git commit -m "chore: bump VERSION to ${{ github.event.inputs.version }}"
            git push origin HEAD:main
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
